import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

const defaultEndpoint = "https://rickandmortyapi.com/api/character";

export async function getServerSideProps() {
  const res = await fetch(defaultEndpoint);
  const data = await res.json();
  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }) {
  const { info, results: defaultResults = [] } = data;

  const [page, updatePage] = useState({
    current: defaultEndpoint,
    next: info?.next,
  });
  const { current, prev } = page;

  const [results, updateResults] = useState(defaultResults);

  useEffect(() => {
    if (current === defaultEndpoint) return;

    async function request() {
      const res = await fetch(current);
      const nextData = await res.json();
      const { info: nextInfo, results: nextResults = [] } = nextData;

      updatePage((prev) => {
        return {
          ...prev,
          ...nextInfo,
        };
      });

      if (!nextInfo?.prev) {
        updateResults(nextResults);
        return;
      }

      updateResults((prev) => {
        return [...prev, ...nextResults];
      });
    }
    request();
  }, [current]);

  function handleLoadMore() {
    updatePage((prev) => {
      return {
        ...prev,
        current: page?.next,
      };
    });
  }

  function handleOnSubmitSearch(e) {
    e.preventDefault();

    const { currentTarget = {} } = e;
    const fields = Array.from(currentTarget?.elements);
    const fieldQuery = fields.find((field) => field.name === "query");

    const value = fieldQuery.value;

    if (value) {
      updatePage({
        current: `https://rickandmortyapi.com/api/character/?name=${value}`,
      });
    }
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Wubba Lubba Dub dub!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Wubba Lubba Dub dub!!</h1>

        <p className={styles.description}>Rick and Morty Wiki</p>

        <form className={styles.search} onSubmit={handleOnSubmitSearch}>
          <input name="query" type="search" />
          <button className={styles.button}>Search</button>
        </form>

        <div className={styles.grid}>
          {results.map((result) => {
            const { id, name, image } = result;
            return (
              <Link
                key={id}
                href="/character/[id]"
                as={`/character/${id}`}
                className={styles.grid}
              >
                <a className={styles.card}>
                  <div>
                    <img width={300} height={300} src={image} />
                  </div>
                  <p className="char-name">{name}</p>
                </a>
              </Link>
            );
          })}
        </div>

        {info?.next && (
          <p className="load-more">
            <button className={styles.button} onClick={handleLoadMore}>
              Load More
            </button>
          </p>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
